import inputIcon from "../../../assets/icon/input.svg";
import selectIcon from "../../../assets/icon/select.svg";
import checkboxIcon from "../../../assets/icon/checkbox.svg";
import fileIcon from "../../../assets/icon/file.svg";
import imgIcon from "../../../assets/icon/picture.svg";
import textIcon from "../../../assets/icon/text.svg";
import { generateUniqueUUID } from "../uitls/index";

export const menuData = [
  {
    componentType: "自定义组件",
    subMenuData: [
      {
        name: "下拉框",
        fieldName: "下拉选择名称",
        componentName: "SelectH",
        componentType: 3,
        icon: selectIcon,
        propertyPanelComponent: "SelectFieldProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 3,
          fieldName: "下拉选择名称",
          requireFlag: 1,
          defaultValue: "",
          tipType: "",
          tipContent: "",
          tipOption: "",
          documentPlace: "",
          abnormalSync: 0,
          abnormalValues: "",
          displayRule: "",
          optionsRule: "",
          options: [
            { value: "异常", key: generateUniqueUUID() },
            { value: "不适用", key: generateUniqueUUID() },
          ],
        },
      },
      {
        name: "评级下拉框",
        fieldName: "评级下拉框",
        componentName: "SelectAbnormalLevel",
        componentType: 12,
        icon: selectIcon,
        propertyPanelComponent: "SelectAbnormalLevelProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 12,
          fieldName: "评级下拉框",
          requireFlag: 1,
          documentPlace: "",
          defaultValue: "",
          options: [
            { value: "正常", key: generateUniqueUUID() },
            { value: "轻微失效", key: generateUniqueUUID() },
            { value: "中等失效", key: generateUniqueUUID() },
            { value: "严重失效", key: generateUniqueUUID() },
          ],
        },
      },
      {
        name: "输入框",
        fieldName: "输入框名称",
        componentName: "Input",
        componentType: 1,
        propertyPanelComponent: "InputFieldProperty",
        icon: inputIcon,
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 1,
          fieldName: "输入框名称",
          requireFlag: 1,
          lengthMax: 30,
          defaultValue: "",
          documentPlace: "",
          tipType: "",
          tipContent: "",
          tipOption: "",
          placeHolder: "请输入内容",
        },
      },
      {
        name: "下拉框+输入框",
        fieldName: "下拉框+输入框",
        componentName: "SelectInput",
        componentType: 14,
        icon: textIcon,
        propertyPanelComponent: "SelectInputProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 14,
          fieldName: "下拉框+输入框",
          defaultValue: "",
          requireFlag: 1,
          documentPlace: "",
          tipType: "",
          tipContent: "",
          tipOption: "",
          lengthMax: 50,
          children: [
            {
              componentType: 3,
              fieldName: "下拉选择名称",
              requireFlag: 1,
              defaultValue: "",
              options: [
                { value: "ISO446", key: generateUniqueUUID() },
                { value: "NAS1638", key: generateUniqueUUID() },
              ],
              __uuid: generateUniqueUUID(10),
            },
            {
              componentType: 1,
              fieldName: "输入框名称",
              requireFlag: 1,
              lengthMax: 50,
              defaultValue: "",
              __uuid: generateUniqueUUID(10),
            },
          ],
        },
      },
      {
        name: "富文本输入框",
        fieldName: "富文本输入框",
        componentName: "RichText",
        componentType: 2,
        propertyPanelComponent: "RichTextFieldProperty",
        icon: inputIcon,
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 2,
          fieldName: "富文本输入框名称",
          requireFlag: 1,
          defaultValue: "",
          documentPlace: "",
          lengthMax: 50,
          tipType: "",
          tipContent: "",
          tipOption: "",
          placeHolder: "请输入内容",
        },
      },
      {
        name: "多选项",
        fieldName: "多选框名称",
        componentName: "CheckBoxH",
        componentType: 4,
        icon: checkboxIcon,
        propertyPanelComponent: "CheckBoxFieldProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 4,
          requireFlag: 1,
          defaultValue: "",
          fieldName: "多选框名称",
          tipType: "",
          tipContent: "",
          tipOption: "",
          abnormalSync: 0,
          documentPlace: "",
          abnormalValues: "",
          displayRule: "",
          optionsRule: "",
          options: [
            { value: "选项1", key: generateUniqueUUID() },
            { value: "选项2", key: generateUniqueUUID() },
          ],
        },
      },
      {
        name: "上传图片",
        fieldName: "上传图片",
        componentName: "UploadImg",
        componentType: 5,
        icon: imgIcon,
        propertyPanelComponent: "UplaodImgFieldProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          lengthMax: 1,
          componentType: 5,
          fieldName: "上传图片",
          requireFlag: 1,
          documentPlace: "",
          defaultValue: "",
        },
      },
      {
        name: "上传附件",
        fieldName: "上传附件",
        componentName: "UploadFile",
        componentType: 6,
        icon: fileIcon,
        propertyPanelComponent: "UplaodFileFieldProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          limit: "1",
          componentType: 6,
          fieldName: "上传文件",
          requireFlag: 1,
          documentPlace: "",
          length: 10,
          defaultValue: "",
        },
      },
      {
        name: "文字&图片提示",
        fieldName: "文字&图片提示",
        componentName: "TextImgTip",
        componentType: 7,
        icon: textIcon,
        propertyPanelComponent: "TextImgTipProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 7,
          fieldName: "文字&图片提示名称",
          requireFlag: 1,
          documentPlace: "",
          defaultValue: "",
          options: undefined,
        },
      },
      {
        name: "组合添加按钮",
        fieldName: "组合添加按钮",
        componentName: "GroupAddButton",
        componentType: 8,
        icon: textIcon,
        propertyPanelComponent: "GroupAddButtonProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          lengthMax: 5,
          componentType: 8,
          fieldName: "组合添加按钮名称",
          requireFlag: 1,
          default: "",
          documentPlace: "",
          options: undefined,
          children: [],
        },
      },
      {
        name: "只读字段",
        fieldName: "只读字段",
        componentName: "ReadOnlyField",
        componentType: 9,
        icon: textIcon,
        propertyPanelComponent: "ReadOnlyFieldProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 9,
          fieldName: "只读字段名称",
          requireFlag: 1,
          defaultValue: "",
          options: [],
          children: [
            {
              __id: 1,
              fieldName: "字段名称",
              sourceType: 1,
              sourceField: "",
              documentPlace: "",
            },
          ],
        },
      },
      {
        name: "Tab栏",
        fieldName: "Tab栏",
        componentName: "TabBar",
        componentType: 10,
        icon: textIcon,
        propertyPanelComponent: "TabBarProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 10,
          fieldName: "Tab栏",
          requireFlag: 1,
          defaultValue: "",
          options: undefined,
          documentPlace: "",
          children: [
            {
              value: "选项1",
              label: "选项1",
              tabComponentModule: null,
            },
            {
              value: "选项2",
              label: "选项2",
              tabComponentModule: null,
            },
          ],
        },
      },
      {
        name: "模块",
        fieldName: "模块",
        componentName: "GroupModule",
        componentType: 11,
        icon: textIcon,
        propertyPanelComponent: "GroupModuleProperty",
        configField: {
          display: 1,
          renderFormat: "normal",
          componentType: 11,
          fieldName: "模块",
          requireFlag: 1,
          defaultValue: "",
          options: undefined,
          documentPlace: "",
          children: [],
        },
      },
    ],
  },
];

export const componentData = menuData
  .reduce((pre, cur) => {
    return pre.concat(cur.subMenuData);
  }, [])
  .sort((a, b) => a.componentType - b.componentType);

export const getComponentDataByType = (componentType) => {
  if (componentData[componentType - 1].componentType === componentType) return componentData[componentType - 1];
  return componentData.find((item) => item.componentType === componentType);
};
